version: '3'

services:
  myapp-mysql:
    image: mariadb:10.5.2-bionic
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=platart
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Del2020
    ports:
      - "3306:3306"

  myapp-main:
    image: alnbuber/platart:1.3
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Del2020
      - DATABASE_NAME=platart
      - DATABASE_PORT=3306
